#!/usr/bin/env python

# Run this before you deploy it on replicate
import os
import sys

# append project directory to path so predict.py can be imported
# sys.path.append('.')
# from predict import MODEL_CACHE
MODEL_CACHE = "cache"

# Make cache folders
if not os.path.exists(MODEL_CACHE):
    os.makedirs(MODEL_CACHE)

# Download GFPGANv1.4
#os.system("cd cache && wget https://github.com/TencentARC/GFPGAN/releases/download/v1.3.0/GFPGANv1.4.pth")

# Left as an excersise to the reader
